name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - feat
  - title: 'ğŸ› Bug Fixes'
    labels:
      - fix
  - title: 'âš¡ Performance'
    labels:
      - perf
  - title: 'ğŸ§¾ Documentation'
    labels:
      - docs
  - title: 'ğŸ§° Maintenance'
    labels:
      - chore
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## What's Changed
  $CHANGES
